spring:
  datasource:
    url: jdbc:mysql://db-8th-team3.cjh70mrazv3k.ap-northeast-2.rds.amazonaws.com:3306/kagongsillok?createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6397

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expire-length: 3600000 # 1시간
      refresh-token-expire-length: 5184000000 # 60일

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  config: classpath:log4j2/log4j2-develop.xml

oauth:
  kakao:
    clientId: ${OAUTH_KAKAO_CLIENT_ID}
    clientSecret: ${OAUTH_KAKAO_CLENT_SECRET}
    authorizationServerHost: https://kauth.kakao.com
    resourceServerHost: https://kapi.kakao.com
